### ISSUE TITLE
Implement alert condition

### ISSUE THREAD

**Issue by swapbyt3s** [swapbyt3s/zenit#15]
This is a proposal.

For example:

```yaml
mysql:
  dsn: root@tcp(127.0.0.1:3306)/
  overflow: true
  slave: true
  status: true
  tables: true
  variables: true
  slowlog:
    enable: true
    log_path: /var/lib/mysql/slow.log
    buffer_size: 100
    buffer_timeout: 60
  auditlog:
    enable: true
    format: xml-old
    log_path: /var/lib/mysql/audit.log
    buffer_size: 100
    buffer_timeout: 60
  alerts:
    readonly:
      enable: true
    lag:
      enable: false
      warning: 10
      critical: 60
      duration: 30
    connections:
      enable: true
      warning: 70
      critical: 90
      duration: 30
os:
  cpu: true
  disk:
    enable: true
    alerts:
    - volume: /var/lib/mysql/
      enable: true
      warning: 75
      critical: 95
      duration: 30
```
- Implemented [YAML](https://github.com/go-yaml/yaml) in #44.
- Duration is a seconds between first encountering a new check.
