### ISSUE TITLE
Auto discover MySQL RDS on AWS

### ISSUE THREAD

**Issue by nstrappazzonc** [swapbyt3s/zenit#92]
```yaml
---
general:
  aws_access_key_id: xxx
  aws_secret_access_key: xxx

inputs:
  rds:
    enable: true
    username: monitor
    password: monitor
    hostname: [dns|instance_name]
    plugins:
      aurora: false
      overflow: true
      slave: true
      status: true
      tables: true
      variables: true
```
